In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr1 + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
matrix1 = np.arange(20).reshape(5,4)
matrix1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
matrix1 + 9

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

#### We can see, when we add matrix1 to a scalar, scalar is added to every element of matrix1 i.e the scalar is duplicated.  

In [12]:
matrix2 = np.arange(20).reshape(4,5)
matrix2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
arr2 = np.arange(5)
arr2

array([0, 1, 2, 3, 4])

In [14]:
arr2 + matrix2

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18],
       [15, 17, 19, 21, 23]])

In [18]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
matrix1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
arr1 + matrix1

ValueError: operands could not be broadcast together with shapes (10,) (5,4) 

#### Arr1 and matrix1 could not be added because neither of them can be broadcasted since there are no common factor in their dimensions.