#### Generating a 1-D array within the range of 1 to 100 of size 15.

In [6]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([65, 28, 51, 19,  5, 42, 73, 46, 72, 64, 56, 75, 27, 51, 83])

#### Generating a matrix of shpae 6X4 and the inputs are within the range 1,100

In [7]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[42, 82, 70, 91],
       [42, 75, 34,  9],
       [33, 99, 84, 72],
       [72, 10, 21, 29],
       [36, 28, 84, 27],
       [68, 49, 66, 80]])

#### Sorting a 1-D array

In [8]:
np.sort(a)

array([ 5, 19, 27, 28, 42, 46, 51, 51, 56, 64, 65, 72, 73, 75, 83])

#### Sorting the previous matrix b, column-wise

In [9]:
np.sort(b,axis=0)

array([[33, 10, 21,  9],
       [36, 28, 34, 27],
       [42, 49, 66, 29],
       [42, 75, 70, 72],
       [68, 82, 84, 80],
       [72, 99, 84, 91]])

#### sorting the matrix b in descending order column wise

In [10]:
np.sort(b,axis=0)[::-1]

array([[72, 99, 84, 91],
       [68, 82, 84, 80],
       [42, 75, 70, 72],
       [42, 49, 66, 29],
       [36, 28, 34, 27],
       [33, 10, 21,  9]])

#### Appending an element on an 1D array

In [11]:
np.append(a,200)

array([ 65,  28,  51,  19,   5,  42,  73,  46,  72,  64,  56,  75,  27,
        51,  83, 200])

#### Appending one at end of each column

In [12]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[42., 82., 70., 91.,  1.],
       [42., 75., 34.,  9.,  1.],
       [33., 99., 84., 72.,  1.],
       [72., 10., 21., 29.,  1.],
       [36., 28., 84., 27.,  1.],
       [68., 49., 66., 80.,  1.]])

#### Creating two 2-D arrays
- First created an 1D array using arange and then reshaping it into 2-D matrix using reshape

In [13]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


#### Concatenating two matrices along the vertical axis(row-wise)
- axis = 0 , refers vertically

In [14]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### Concatenating two matrices along the horizontal axis(column-wise)
- axis = 1 , refers horizontally

In [15]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

#### Finding only unique elements in an array

In [16]:
e=np.array([1,2,3,4,42,45,342,2,3,2,2])
np.unique(e)

array([  1,   2,   3,   4,  42,  45, 342])

#### Expanding the dimensions of an array column wise

In [17]:
a

array([65, 28, 51, 19,  5, 42, 73, 46, 72, 64, 56, 75, 27, 51, 83])

In [18]:
np.expand_dims(a,axis=1)

array([[65],
       [28],
       [51],
       [19],
       [ 5],
       [42],
       [73],
       [46],
       [72],
       [64],
       [56],
       [75],
       [27],
       [51],
       [83]])

#### Filtering using where in an array

In [19]:
np.where(a>50)

(array([ 0,  2,  6,  8,  9, 10, 11, 13, 14]),)

#### Filtering using where.
- Here np.where(a>50,0,a) means if an element if greater than 50 than print the element or else print 0 instead

In [20]:
np.where(a>50,0,a)

array([ 0, 28,  0, 19,  5, 42,  0, 46,  0,  0,  0,  0, 27,  0,  0])

In [21]:
np.where(a%2==0,0,a)

array([65,  0, 51, 19,  5,  0, 73,  0,  0,  0,  0, 75, 27, 51, 83])

#### Returns the index with max value

In [22]:
np.argmax(a)

14

#### Returns the index of maximum value row-wise

In [23]:
np.argmax(b,axis=0)

array([3, 2, 2, 0])

In [24]:
b

array([[42, 82, 70, 91],
       [42, 75, 34,  9],
       [33, 99, 84, 72],
       [72, 10, 21, 29],
       [36, 28, 84, 27],
       [68, 49, 66, 80]])

#### Returns the index of maximum value column-wise

In [25]:
np.argmax(b,axis=1)

array([3, 1, 1, 0, 2, 3])

#### Return the index of minimum value(since b is matrix and no axis is mentioned it wise give the index of min value from the matrix)

In [26]:
np.argmin(b)

7

#### Return the index of minimum value(since b is matrix and no axis is mentioned it wise give the index of max value from the matrix)

In [27]:
np.argmax(b)

9

In [28]:
a

array([65, 28, 51, 19,  5, 42, 73, 46, 72, 64, 56, 75, 27, 51, 83])

#### Cumulative sum

In [30]:
np.cumsum(a)

array([ 65,  93, 144, 163, 168, 210, 283, 329, 401, 465, 521, 596, 623,
       674, 757])

In [31]:
b

array([[42, 82, 70, 91],
       [42, 75, 34,  9],
       [33, 99, 84, 72],
       [72, 10, 21, 29],
       [36, 28, 84, 27],
       [68, 49, 66, 80]])

In [32]:
np.cumsum(b)

array([  42,  124,  194,  285,  327,  402,  436,  445,  478,  577,  661,
        733,  805,  815,  836,  865,  901,  929, 1013, 1040, 1108, 1157,
       1223, 1303])

In [33]:
np.cumsum(b,axis=0)

array([[ 42,  82,  70,  91],
       [ 84, 157, 104, 100],
       [117, 256, 188, 172],
       [189, 266, 209, 201],
       [225, 294, 293, 228],
       [293, 343, 359, 308]])

#### Cumulative product

In [34]:
np.cumprod(a)

array([                  65,                 1820,                92820,
                    1763580,              8817900,            370351800,
                27035681400,        1243641344400,       89542176796800,
           5730699314995200,   320919161639731200,  5622193049270288384,
        4225259740621373440, -5872682112824573952, -7817269447991296000])

### Perecentile

In [36]:
a

array([65, 28, 51, 19,  5, 42, 73, 46, 72, 64, 56, 75, 27, 51, 83])

In [37]:
np.percentile(a,100)

83.0

In [38]:
np.percentile(a,50)

51.0

#### Fliping a numpy array

In [44]:
a

array([65, 28, 51, 19,  5, 42, 73, 46, 72, 64, 56, 75, 27, 51, 83])

In [45]:
np.flip(a)

array([83, 51, 27, 75, 56, 64, 72, 46, 73, 42,  5, 19, 51, 28, 65])

In [46]:
b


array([[42, 82, 70, 91],
       [42, 75, 34,  9],
       [33, 99, 84, 72],
       [72, 10, 21, 29],
       [36, 28, 84, 27],
       [68, 49, 66, 80]])

In [47]:
np.flip(b)

array([[80, 66, 49, 68],
       [27, 84, 28, 36],
       [29, 21, 10, 72],
       [72, 84, 99, 33],
       [ 9, 34, 75, 42],
       [91, 70, 82, 42]])

In [48]:
np.flip(b,axis=0)

array([[68, 49, 66, 80],
       [36, 28, 84, 27],
       [72, 10, 21, 29],
       [33, 99, 84, 72],
       [42, 75, 34,  9],
       [42, 82, 70, 91]])

In [49]:
a

array([65, 28, 51, 19,  5, 42, 73, 46, 72, 64, 56, 75, 27, 51, 83])

#### Here we changed the values of index 0,1 in a using put(this is a permanent change)

In [50]:
np.put(a,[0,1],[110,530])

In [51]:
a

array([110, 530,  51,  19,   5,  42,  73,  46,  72,  64,  56,  75,  27,
        51,  83])

#### Deleting the value of mentioned index from a

In [52]:
np.delete(a,0)

array([530,  51,  19,   5,  42,  73,  46,  72,  64,  56,  75,  27,  51,
        83])

In [53]:
np.delete(a,[0,4,6])

array([530,  51,  19,  42,  46,  72,  64,  56,  75,  27,  51,  83])

#### Returns the union of two arrays

In [54]:
n1=np.array([1,2,3,4,5])
n2=np.array([6,7,8,9,10])
np.union1d(n1,n2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Returns the intersection of two arrays

In [55]:
np.intersect1d(n1,n2)

array([], dtype=int64)

In [57]:
a

array([110, 530,  51,  19,   5,  42,  73,  46,  72,  64,  56,  75,  27,
        51,  83])

#### Here we have set a range between 25 and 75
- If a value is less than 25 then it is replaced by 25 and if it is greater than 75 then it is replaced by 75 and if it's between then the number is taken as it is.

In [58]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 51, 25, 25, 42, 73, 46, 72, 64, 56, 75, 27, 51, 75])