In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn import datasets

In [3]:
datasets=datasets.load_iris()

In [4]:
X=datasets['data']
y=datasets['target']

In [5]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y , test_size = 0.33 , random_state = 56)

In [6]:
pca = PCA(n_components = 3)

In [7]:
X_train = pca.fit_transform(X_train)

In [8]:
X_train

array([[-2.71955569,  0.29199577,  0.07474219],
       [-0.36794909,  1.28476539, -0.27856878],
       [-2.50447023, -1.03348296,  0.14970619],
       [ 0.65879533,  1.1919785 ,  0.53829222],
       [-2.35566707, -0.07390723,  0.08561152],
       [-2.43272687, -0.44544091,  0.15892245],
       [-0.05361917,  0.26759941,  0.08184895],
       [-2.17972401, -0.6878165 ,  0.16019465],
       [ 1.32547085,  0.59243006,  0.50419637],
       [ 0.62878907,  0.10350087,  0.1227918 ],
       [-2.4787807 , -0.16976254, -0.08899967],
       [ 2.71752551, -0.60213459, -0.21022722],
       [ 2.42573267, -0.21862435,  0.31473845],
       [ 2.49348291, -0.50162905, -0.45443254],
       [ 1.3279297 , -0.42185044, -0.24421252],
       [ 2.52779715, -0.34171056,  0.4968381 ],
       [-2.18877064, -0.04484247,  0.0293862 ],
       [ 1.87785403, -0.10341488,  0.12298679],
       [-2.77047526,  0.20999099,  0.00847406],
       [ 0.75731741, -0.02090891, -0.21261612],
       [-2.453776  , -0.30894534, -0.087

In [9]:
pca.components_

array([[ 0.34961507, -0.0995681 ,  0.85881076,  0.36097032],
       [-0.66349364, -0.72833445,  0.15655409,  0.06925268],
       [-0.58333995,  0.59996996,  0.07934129,  0.54171534]])

In [10]:
pca.explained_variance_ratio_

array([0.91767805, 0.05879079, 0.01855211])