In [ ]:
import numpy as np

In [ ]:
x = np.array([1,4,6])
y = np.array([5,7,4])

In [ ]:
x + y

array([ 6, 11, 10])

In [ ]:
x - y

array([-4, -3,  2])

In [ ]:
x * y

array([ 5, 28, 24])

In [ ]:
np.linalg.norm(x)

7.280109889280518

In [ ]:
np.linalg.norm(y)

9.486832980505138

In [ ]:
np.dot(x,y)

57

In [ ]:
A = np.array([[3,4],[6,4],[4,7]])
A

array([[3, 4],
       [6, 4],
       [4, 7]])

In [ ]:
B = np.array([[6,8],[4,9],[8,2]])
B

array([[6, 8],
       [4, 9],
       [8, 2]])

In [ ]:
np.add(A,B)

array([[ 9, 12],
       [10, 13],
       [12,  9]])

In [ ]:
np.subtract(A,B)

array([[-3, -4],
       [ 2, -5],
       [-4,  5]])

In [ ]:
np.multiply(A,B)

array([[18, 32],
       [24, 36],
       [32, 14]])

In [ ]:
X1 = np.array([[4,7,6],[12,2,4]])
X1

array([[ 4,  7,  6],
       [12,  2,  4]])

In [ ]:
C1=np.dot(A,X1)
C1

array([[ 60,  29,  34],
       [ 72,  50,  52],
       [100,  42,  52]])

In [ ]:
det = np.linalg.det(C1)

In [ ]:
np.linalg.inv(C1)

LinAlgError: Singular matrix

In [ ]:
A = np.array([[2,-2,3],[1,1,2],[1,3,-1]])
A

array([[ 2, -2,  3],
       [ 1,  1,  2],
       [ 1,  3, -1]])

In [ ]:
eigen_values ,eigen_vector = np.linalg.eig(A)

In [ ]:
eigen_values

array([ 3.12655215,  1.62648553, -2.75303768])

In [ ]:
eigen_vector

array([[-0.32817447, -0.59524195, -0.59007098],
       [-0.72444689,  0.63241473, -0.25159039],
       [-0.60619981,  0.49572031,  0.7671496 ]])